version: 2.1
jobs:
  build:
    working_directory: ~/open_triviaa/client
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'circleci-project-setup' ]; then
              npm run build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    working_directory: ~/open_triviaa/client
    docker:
      - image: circleci/node:12-browsers
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: |
            if [ $CIRCLE_BRANCH = 'circleci-project-setup' ]; then
              npm run test
            fi

  deploy:
    working_directory: ~/open_triviaa/client
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'circleci-project-setup' ]; then
              aws s3 sync build s3://open-trivia-anthony-nucci --delete --exact-timestamps;
            fi
workflows:
  build_test_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - circleci-project-setup
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - circleci-project-setup

      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - circleci-project-setup
# hi
